[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[edge_functions]]
path = "/api/keys"
function = "keys"

[dev]
command = "pnpm dev:watch"
targetPort = 5173
port = 8888
publish = "dist"
autoLaunch = true
envFiles = [".env"]

[build]
command = "pnpm build:start"
envFiles = [".env.production"]
publish = "dist"
